//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningWEBAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int courseid { get; set; }
        public string coursename { get; set; }
        public byte[] attachment { get; set; }
    }
}
