//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningWEBAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public int semesterid { get; set; }
        public string semestername { get; set; }
    }
}
